[backend]
host = '${RPC_HOST}:${RPC_PORT}'
rpcauth = '${RPC_USER}:${RPC_PASS}'
zmq_host = 'tcp://${RPC_HOST}:28332'   # bitcoind zmqpubhashblock topic; instant new-block notify
poll_interval = 600000

[pogolo]
host = '0.0.0.0'
port = 5661
http_port = 5662
tag = '${TAG}'
pool_address = '${ADDRESS}'
default_difficulty = ${DIFFICULTY}
disable_vardiff = false
ignore_suggested_difficulty = false
job_interval = 3600
